[package]
name = "nft-login"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
chrono = "0.4"
openidconnect = "2.1.0"
rocket = "0.5.0-rc.1"
serde_json = "1.0"
