[default]
ident = "nft-login"
[default.node_provider]
default = "https://kovan.infura.io/v3/43"
kovan = "https://kovan.infura.io/v3/43"
okt = "https://exchaintestrpc.okex.org"
clv = "https://rpc-3.clover.finance"
heco = "https://http-testnet.hecochain.com"
main = "https://cloudflare-eth.com"

[debug]
port = 8000
ext_hostname = "http://localhost:8000"

[release]
address = "0.0.0.0"
port = 8080
ext_hostname = "https://nft-login.example.com"
rsa_pem = "../do-not-use.pem"
