[default]
ident = "nft-login"
node_provider = "https://cloudflare-eth.com"

[debug]
port = 8000
ext_hostname = "http://localhost:8000"

[release]
address = "0.0.0.0"
port = 8080
ext_hostname = "https://nft-login.example.com"
rsa_pem = "../do-not-use.pem"
